import { OraclePluginFields } from "./types";

export const oraclePluginRegistry = {
  plugins: [
    {
      expectedOutputs: ["comparison.json"],
      family: "ICD",
      fixtureRoot: "test/oracles/coding",
      inputKind: "coding-preview",
      kind: "fixture-backed",
      normalizationRules: ["normalizePaths", "normalizeTimestamps"],
      passFailRule:
        "Coding evaluation matches SDICD/SDKH/SDKRW fixture expectations.",
      workingDirectory: ".",
    },
    {
      expectedOutputs: ["comparison.json"],
      family: "TSS",
      fixtureRoot: "test/oracles/tss",
      inputKind: "tss-selection",
      kind: "fixture-backed",
      normalizationRules: ["normalizePaths", "normalizeTimestamps"],
      passFailRule:
        "TSS appointment listing and selection behavior matches fixture expectations.",
      workingDirectory: ".",
    },
    {
      command: "tools/oracles/kvdt/run.ts",
      expectedOutputs: ["report.json", "stdout.txt"],
      family: "KVDT",
      fixtureRoot: "test/oracles/kvdt",
      inputKind: "kvdt-export",
      kind: "executable-backed",
      normalizationRules: ["normalizePaths", "normalizeTimestamps"],
      passFailRule: "No blocking validator findings.",
      reportParser: "tools/oracles/kvdt/parseReport.ts",
      workingDirectory: ".",
    },
    {
      command: "tools/oracles/fhir/run.ts",
      expectedOutputs: ["report.json"],
      family: "eAU",
      fixtureRoot: "test/oracles/eau",
      inputKind: "fhir-xml",
      kind: "executable-backed",
      normalizationRules: ["normalizePaths", "normalizeValidatorNoise"],
      passFailRule:
        "FHIR validator exits successfully with no error severity findings.",
      reportParser: "tools/oracles/fhir/parseReport.ts",
      workingDirectory: ".",
    },
    {
      command: "tools/oracles/fhir/run.ts",
      expectedOutputs: ["report.json"],
      family: "eRezept",
      fixtureRoot: "test/oracles/erp",
      inputKind: "fhir-xml",
      kind: "executable-backed",
      normalizationRules: ["normalizePaths", "normalizeValidatorNoise"],
      passFailRule:
        "FHIR validator exits successfully with no error severity findings.",
      reportParser: "tools/oracles/fhir/parseReport.ts",
      workingDirectory: ".",
    },
    {
      command: "tools/oracles/fhir/run.ts",
      expectedOutputs: ["report.json"],
      family: "eVDGA",
      fixtureRoot: "test/oracles/evdga",
      inputKind: "fhir-xml",
      kind: "executable-backed",
      normalizationRules: ["normalizePaths", "normalizeValidatorNoise"],
      passFailRule:
        "FHIR validator exits successfully with no error severity findings.",
      reportParser: "tools/oracles/fhir/parseReport.ts",
      workingDirectory: ".",
    },
    {
      expectedOutputs: ["comparison.json"],
      family: "BFB",
      fixtureRoot: "test/oracles/bfb",
      inputKind: "print-artifact",
      kind: "fixture-backed",
      normalizationRules: ["normalizePdfMetadata", "normalizeRenderTimestamps"],
      passFailRule:
        "Rendered output matches fixture expectations and barcode checks.",
      workingDirectory: ".",
    },
    {
      command: "tools/oracles/bmp/run.ts",
      expectedOutputs: ["xsd-report.json", "fixture-report.json"],
      family: "BMP",
      fixtureRoot: "test/oracles/bmp",
      inputKind: "bmp-xml",
      kind: "xsd-backed",
      normalizationRules: ["normalizePaths", "normalizeXmlWhitespace"],
      passFailRule: "XSD validation passes and fixture parity holds.",
      reportParser: "tools/oracles/bmp/parseReport.ts",
      workingDirectory: ".",
    },
    {
      expectedOutputs: ["comparison.json"],
      family: "Heilmittel",
      fixtureRoot: "test/oracles/heilmittel",
      inputKind: "heilmittel-order",
      kind: "fixture-backed",
      normalizationRules: ["normalizePaths", "normalizeRenderTimestamps"],
      passFailRule:
        "Order evaluation matches official KBV Heilmittel prueffall fixtures and rule outcomes.",
      workingDirectory: ".",
    },
  ],
  schema: OraclePluginFields,
} as const;
