import { OraclePluginFields } from "./types";

export const oraclePluginRegistry = {
  schema: OraclePluginFields,
  plugins: [
    {
      family: "ICD",
      kind: "fixture-backed",
      inputKind: "coding-preview",
      fixtureRoot: "test/oracles/coding",
      workingDirectory: ".",
      expectedOutputs: ["comparison.json"],
      normalizationRules: ["normalizePaths", "normalizeTimestamps"],
      passFailRule: "Coding evaluation matches SDICD/SDKH/SDKRW fixture expectations.",
    },
    {
      family: "TSS",
      kind: "fixture-backed",
      inputKind: "tss-selection",
      fixtureRoot: "test/oracles/tss",
      workingDirectory: ".",
      expectedOutputs: ["comparison.json"],
      normalizationRules: ["normalizePaths", "normalizeTimestamps"],
      passFailRule: "TSS appointment listing and selection behavior matches fixture expectations.",
    },
    {
      family: "KVDT",
      kind: "executable-backed",
      inputKind: "kvdt-export",
      fixtureRoot: "test/oracles/kvdt",
      command: "tools/oracles/kvdt/run.ts",
      workingDirectory: ".",
      expectedOutputs: ["report.json", "stdout.txt"],
      reportParser: "tools/oracles/kvdt/parseReport.ts",
      normalizationRules: ["normalizePaths", "normalizeTimestamps"],
      passFailRule: "No blocking validator findings.",
    },
    {
      family: "eAU",
      kind: "executable-backed",
      inputKind: "fhir-xml",
      fixtureRoot: "test/oracles/eau",
      command: "tools/oracles/fhir/run.ts",
      workingDirectory: ".",
      expectedOutputs: ["report.json"],
      reportParser: "tools/oracles/fhir/parseReport.ts",
      normalizationRules: ["normalizePaths", "normalizeValidatorNoise"],
      passFailRule: "FHIR validator exits successfully with no error severity findings.",
    },
    {
      family: "eRezept",
      kind: "executable-backed",
      inputKind: "fhir-xml",
      fixtureRoot: "test/oracles/erp",
      command: "tools/oracles/fhir/run.ts",
      workingDirectory: ".",
      expectedOutputs: ["report.json"],
      reportParser: "tools/oracles/fhir/parseReport.ts",
      normalizationRules: ["normalizePaths", "normalizeValidatorNoise"],
      passFailRule: "FHIR validator exits successfully with no error severity findings.",
    },
    {
      family: "BFB",
      kind: "fixture-backed",
      inputKind: "print-artifact",
      fixtureRoot: "test/oracles/bfb",
      workingDirectory: ".",
      expectedOutputs: ["comparison.json"],
      normalizationRules: ["normalizePdfMetadata", "normalizeRenderTimestamps"],
      passFailRule: "Rendered output matches fixture expectations and barcode checks.",
    },
    {
      family: "BMP",
      kind: "xsd-backed",
      inputKind: "bmp-xml",
      fixtureRoot: "test/oracles/bmp",
      command: "tools/oracles/bmp/run.ts",
      workingDirectory: ".",
      expectedOutputs: ["xsd-report.json", "fixture-report.json"],
      reportParser: "tools/oracles/bmp/parseReport.ts",
      normalizationRules: ["normalizePaths", "normalizeXmlWhitespace"],
      passFailRule: "XSD validation passes and fixture parity holds.",
    },
    {
      family: "Heilmittel",
      kind: "fixture-backed",
      inputKind: "heilmittel-order",
      fixtureRoot: "test/oracles/heilmittel",
      workingDirectory: ".",
      expectedOutputs: ["comparison.json"],
      normalizationRules: ["normalizePaths", "normalizeRenderTimestamps"],
      passFailRule: "Order evaluation matches official KBV Heilmittel prueffall fixtures and rule outcomes.",
    },
  ],
} as const;
